#!/bin/sh

### Schedule a daily reboot at 04:08 + random amount of seconds for time scattering # 20170514 | Nk
mkdir -p /etc/crontabs ; touch /etc/crontabs/root
sed "\| \* \* \* .*reboot$|d" -i /etc/crontabs/root
echo "8 4 * * * sleep $(( $RANDOM % 6480)) &&  touch /etc/banner && reboot >/dev/null 2>&1" >> /etc/crontabs/root
